services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
            - POSTGRES_DB=auctions
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postresql/data
volumes:
    pgdata:
